import {readPdf} from './pdf-reader.js';
import {fixed,round,money,gross,crateCost,unitParts,recommend,realizedMarkup,discountSale,recommendedDiscount} from './money.js';
import {renderPages} from './sign-canvas.js';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={doc:null,view:'document',selected:new Set(),signs:[],perPage:4,canvases:[],editProducts:null,busy:false};
let prefs={storeName:'מינימרקט שלום',markup:'25'};
try{const saved=JSON.parse(localStorage.getItem('coca-prefs-v1')||'null');if(saved && typeof saved.storeName==='string' && typeof saved.markup==='string')prefs={storeName:saved.storeName.slice(0,45),markup:saved.markup};}catch{}
let toastTimer,previewTimer;
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3500);}
function notice(text){$('#notice').textContent=text;$('#notice').hidden=!text;}
function decimal(s){return String(s??'').trim().replace(',','.');}
function positiveInt(s,label,max=10000){if(!/^\d+$/.test(String(s))||Number(s)<1||Number(s)>max)throw new Error(label+' חייב להיות מספר שלם וחיובי');return Number(s);}
function amount(s,label,allowZero=false){let v;try{v=fixed(decimal(s));}catch{throw new Error('יש להזין '+label+' תקין');}if(v<0||(!allowZero&&v===0))throw new Error(label+' חייב להיות חיובי');return v;}
function mark(s){const v=amount(s,'אחוז רווח',true);if(v>100000)throw new Error('אחוז הרווח גדול מ־1,000');return v;}
function rowById(id){return state.doc.rows.find(r=>r.id===id);}
function quantity(row){return new Intl.NumberFormat('he-IL',{maximumFractionDigits:3}).format(row.quantityMilli/1000);}
function showView(view){if(state.busy)return;state.view=view;$('#document-view').hidden=view!=='document';$('#signs-view').hidden=view!=='signs';for(const id of ['document','signs']){$('#'+id+'-tab').classList.toggle('active',id===view);$('#'+id+'-tab').setAttribute('aria-current',id===view?'page':'false');}updateSelection();if(view==='signs')renderSigns();window.scrollTo({top:0,behavior:'smooth'});}
function updateCounts(){$('#sign-count').textContent=state.signs.length;$('#signs-tab').disabled=!state.doc;}
function updateSelection(){$('#selection-bar').hidden=state.view!=='document'||state.selected.size===0||state.busy;$('#selected-label').textContent=`${state.selected.size} מוצרים נבחרו`;$('#shared-sign').hidden=state.selected.size<2;}
function pairs(items){return '<dl class="breakdown">'+items.map(([label,value,strong])=>`<dt class="${strong?'strong':''}">${esc(label)}</dt><dd class="${strong?'strong':''}">${esc(value)}</dd>`).join('')+'</dl>';}
function renderDocument(){
  const d=state.doc,s=d.summary;
  $('#upload-panel').hidden=true;$('#document-content').hidden=false;
  $('#document-content').innerHTML=`<div class="document-banner"><div><h1>התעודה שלך מוכנה</h1><p class="document-meta">תעודה ${esc(d.number||'ללא מספר מזוהה')} · ${esc(d.date)} · ${d.rows.length} מוצרים</p><span class="check-badge">✓ החשבון תואם לתעודה</span></div><button class="secondary" data-action="upload">תעודה אחרת</button></div>
  <details class="summary"><summary>סה״כ בתעודה ${esc(money(s.total))} · הצגת הסיכום</summary><div class="summary-content">${pairs([['סחורה לפני הנחות',money(s.gross)],['הנחות',money(s.discount)],['ערך אריזות',money(s.packaging)],['מס קנייה',money(s.tax)],['פיקדון',money(s.deposit)],['הפרשי עיגול לפני מע״מ',money(s.rounding)],['לפני מע״מ',money(s.beforeVat),true],[`מע״מ ${d.vatBp/100}%`,money(s.vat)],['סה״כ כולל מע״מ',money(s.total),true]])}<p class="help">מחיר הארגז מחושב מסכום שורת המוצר הכולל. הפרש העיגול הכללי נשאר בסיכום ואינו משויך למוצר. עיגול המחירים להצגה עשוי ליצור הבדל של אגורות בסכימת המחירים המוצגים.</p></div></details>
  <div class="products-heading"><h2>מחיר סופי לארגז</h2><span>כולל הנחות, מע״מ וכל החיובים</span></div><div class="product-grid">${d.rows.map(r=>`<article class="product-card" data-row="${r.id}"><div class="product-top"><input type="checkbox" aria-label="בחר ${esc(r.name)}" id="choose-${r.id}" data-select="${r.id}"><label for="choose-${r.id}"><h3>${esc(r.name)}</h3><span class="product-code">קוד ${esc(r.code)} · ${quantity(r)} אריזות בתעודה</span></label></div><div class="product-price"><div><div class="price-large">${esc(money(round(crateCost(r,d.vatBp))))}</div><div class="price-caption">לארגז / אריזת ספק אחת · כולל הכול</div></div>${r.discountBp?`<span class="discount-tag">${r.discountBp/100}% הנחת ספק</span>`:''}</div><div class="product-actions"><button class="secondary" data-sign="${r.id}">＋ הכנת שלט</button><span class="price-caption">לפי האריזה בתעודה</span></div><details><summary>איך המחיר מחושב?</summary>${pairs([['סחורה לפני הנחה — כל השורה',money(r.gross)],['הנחת ספק',money(r.discount)],['ערך אריזות',money(r.packaging)],['מס קנייה',money(r.tax)],['פיקדון',money(r.deposit)],['סכום השורה לפני מע״מ',money(r.total),true],[`מע״מ ${d.vatBp/100}% על השורה`,money(round(gross(r.total,d.vatBp))-r.total)],['סכום השורה כולל מע״מ',money(round(gross(r.total,d.vatBp))),true],['מחלקים במספר אריזות הספק',quantity(r)],['מחיר סופי לאריזה',money(round(crateCost(r,d.vatBp))),true]])}<p class="help">ההנחה כבר נוכתה. הפיקדון, האריזות ומס הקנייה כבר כלולים בסכום השורה — הם אינם מתווספים שוב.</p></details></article>`).join('')}</div>`;
  updateCounts();
}
function pickFile(){if(state.busy)return;if(state.signs.length && !confirm('בחירת תעודה חדשה תחליף את התעודה והשלטים הפעילים. להמשיך?'))return;$('#pdf-file').value='';$('#pdf-file').click();}
async function loadFile(file){
  if(!file)return;notice('');state.busy=true;updateSelection();$('#loading').hidden=false;$('#upload-panel').hidden=true;$('#document-content').hidden=true;$('#upload-button').disabled=true;
  try{const doc=await readPdf(file,(n,total)=>$('#loading-label').textContent=`קורא ובודק עמוד ${n} מתוך ${total}…`);state.doc=doc;state.signs=[];state.selected.clear();renderDocument();toast('התעודה נקראה והסכומים אומתו');}
  catch(e){notice('לא ניתן לאמת את התעודה. '+(e.name==='PasswordException'?'הקובץ מוגן בסיסמה. יש לבחור קובץ לא מוגן.':e.message)+' לא הוצגו מחירים חדשים.');$('#upload-panel').hidden=!!state.doc;$('#document-content').hidden=!state.doc;}
  finally{state.busy=false;$('#loading').hidden=true;$('#upload-button').disabled=false;updateSelection();}
}
function createSign(ids){return {id:crypto.randomUUID(),productIds:ids,units:Object.fromEntries(ids.map(id=>[id,''])),kind:'unit',title:ids.length===1?rowById(ids[0]).name:'',price:'',qty:'2',pct:'',oldPrice:'',markup:prefs.markup,rounding:'exact',note:'',validUntil:''};}
function addSigns(shared,ids=[...state.selected]){if(!ids.length)return;if(state.signs.length+(shared?1:ids.length)>24){toast('אפשר להכין עד 24 שלטים בכל פעם');return;}state.signs.push(...(shared?[createSign(ids)]:ids.map(id=>createSign([id]))));state.selected.clear();document.querySelectorAll('[data-select]').forEach(i=>{i.checked=false;i.closest('.product-card').classList.remove('selected');});updateCounts();showView('signs');}
function validateUnits(sign){if(!sign.productIds.length)throw new Error('יש לבחור לפחות מוצר אחד');return sign.productIds.map(id=>({row:rowById(id),units:positiveInt(sign.units[id],'מספר הבקבוקים')}));}
function basis(sign,qty){const rows=validateUnits(sign);const m=mark(sign.markup);const recommendations=rows.map(({row,units})=>({row,units,...recommend(row,state.doc.vatBp,units,m,qty,sign.rounding)}));return recommendations.reduce((best,x)=>x.cents>best.cents?x:best);}
function recommendation(sign){const q=sign.kind==='bundle'?positiveInt(sign.qty,'כמות במבצע',1000):1;const b=basis(sign,q);if(sign.kind!=='pct')return {...b,type:'price',value:b.cents};
  const old=amount(sign.oldPrice,'מחיר רגיל');
  // A shared percentage must satisfy every product independently, including
  // products with different deposits or pack sizes.
  const candidates=validateUnits(sign).map(({row,units})=>({row,units,value:recommendedDiscount(row,state.doc.vatBp,units,mark(sign.markup),old,sign.rounding)}));
  return {...candidates.reduce((best,x)=>x.value<best.value?x:best),type:'pct'};
}
function saleFor(sign,row,units){if(sign.kind!=='pct')return amount(sign.price,'מחיר מכירה');return discountSale(row,state.doc.vatBp,units,amount(sign.oldPrice,'מחיר רגיל'),amount(sign.pct,'אחוז הנחה'));}
function signValidity(sign){try{const rows=validateUnits(sign);if(!sign.title.trim())throw new Error('יש להזין כותרת לשלט');const q=sign.kind==='bundle'?positiveInt(sign.qty,'כמות במבצע',1000):1;for(const r of rows)saleFor(sign,r.row,r.units);if(sign.oldPrice && sign.kind!=='pct' && amount(sign.oldPrice,'מחיר קודם')<=amount(sign.price,'מחיר מכירה'))throw new Error('המחיר הקודם צריך להיות גבוה ממחיר המבצע');if(sign.validUntil && !/^\d{4}-\d{2}-\d{2}$/.test(sign.validUntil))throw new Error('התאריך אינו תקין');return {ok:true,rows,q};}catch(e){return {ok:false,error:e.message};}}
function input(sign,key,label,options={}){return `<label>${esc(label)}<input data-field="${key}" data-id="${sign.id}" value="${esc(sign[key])}" ${options.type==='date'?'type="date"':`type="text" ${options.text?'':'inputmode="'+(options.integer?'numeric':'decimal')+'"'}`} ${options.max?`maxlength="${options.max}"`:''} ${options.placeholder?`placeholder="${esc(options.placeholder)}"`:''}></label>`;}
function editor(sign,index){return `<article class="sign-card" data-editor="${sign.id}"><div class="sign-heading"><strong>שלט ${index+1} · ${sign.productIds.length} מוצרים</strong><button class="delete-sign" data-delete="${sign.id}">הסרת השלט</button></div><div class="sign-products"><div class="product-edit-head"><span>בקבוקים באריזת הספק</span><button data-edit-products="${sign.id}">שינוי מוצרים</button></div>${sign.productIds.map(id=>{const row=rowById(id);return `<div class="sign-product-row"><span>${esc(row.name)}<small>אריזה: ${esc(money(round(crateCost(row,state.doc.vatBp))))} כולל הכול</small><small id="unit-${sign.id}-${id}"></small></span><label>מספר בקבוקים *<input type="text" inputmode="numeric" data-units="${id}" data-id="${sign.id}" value="${esc(sign.units[id])}" placeholder="לדוגמה: 24" required></label></div>`;}).join('')}<p class="help">מספר הבקבוקים בארגז אחד, לא מספר הארגזים בתעודה. הכמות משמשת רק לשלט הזה.</p></div>${input(sign,'title','כותרת השלט',{text:true,max:180,placeholder:'שם המוצר או קבוצת המוצרים'})}<div class="kind-picker" role="group" aria-label="סוג מבצע">${[['unit','מחיר לבקבוק'],['bundle','כמות במחיר'],['pct','אחוז הנחה']].map(([kind,label])=>`<button data-kind="${kind}" data-id="${sign.id}" class="${sign.kind===kind?'active':''}" aria-pressed="${sign.kind===kind}">${label}</button>`).join('')}</div><div class="fields-row ${sign.kind==='bundle'?'three':''}">${sign.kind==='bundle'?input(sign,'qty','כמות במבצע',{integer:true}):''}${sign.kind==='pct'?input(sign,'pct','הנחה על המוצר (%)'):input(sign,'price',sign.kind==='bundle'?'מחיר כולל למבצע (₪)':'מחיר לבקבוק (₪)')}${input(sign,'oldPrice',sign.kind==='pct'?'מחיר רגיל לבקבוק (₪)':sign.kind==='bundle'?'במקום — לכל המבצע (רשות)':'במקום (רשות)')}</div>${sign.kind==='pct'?'<p class="help">ההנחה לצרכן חלה על מחיר המוצר בלבד. הפיקדון וערך האריזה אינם מוזלים.</p>':''}<div class="markup-row">${input(sign,'markup','אחוז רווח (%)')}<p>תוספת לעלות, כמו בייטבתה. הרווח מחושב על הסחורה ומס הקנייה. פיקדון וערך אריזה מצטרפים פעם אחת, ללא תוספת רווח.</p></div><label class="rounding-field"><input type="checkbox" data-rounding="${sign.id}" ${sign.rounding==='ninety'?'checked':''}>המלצה עם סיומת ‎.90 — עיגול כלפי מעלה</label><div id="rec-${sign.id}"></div><div id="profit-${sign.id}" class="actual-profit"></div><div class="fields-row">${input(sign,'validUntil','בתוקף עד (רשות)',{type:'date'})}${input(sign,'note','הערה (רשות)',{text:true,max:120})}</div><p id="error-${sign.id}" class="sign-error" hidden></p></article>`;}
function updateRecommendation(sign){
  const box=$('#rec-'+sign.id);if(!box)return;
  for(const id of sign.productIds){try{const units=positiveInt(sign.units[id],'מספר הבקבוקים');const p=unitParts(rowById(id),state.doc.vatBp,units);$('#unit-'+sign.id+'-'+id).textContent='עלות לבקבוק: '+money(round(p.total));}catch{$('#unit-'+sign.id+'-'+id).textContent='';}}
  try{const r=recommendation(sign);box.innerHTML=`<div class="recommendation"><div>המלצה: <strong>${r.type==='pct'?r.value+'%':sign.kind==='bundle'?`${sign.qty} ב־${esc(money(r.value))}`:esc(money(r.value))+' לבקבוק'}</strong><small>${sign.productIds.length>1?'מבוסס על המוצר שמצריך את המחיר הגבוה ביותר: '+esc(r.row.name):'כולל מע״מ, פיקדון וערך אריזה'}</small></div><button data-apply="${sign.id}">השתמש</button></div>`;}catch(e){box.innerHTML=`<div class="recommendation missing">${esc(e.message)}</div>`;}
  const out=$('#profit-'+sign.id);out.textContent='';out.classList.remove('warning');
  try{const items=validateUnits(sign);const q=sign.kind==='bundle'?positiveInt(sign.qty,'כמות במבצע',1000):1;const rates=items.map(({row,units})=>realizedMarkup(row,state.doc.vatBp,units,q,saleFor(sign,row,units))).filter(n=>n!==null);if(rates.length){const min=Math.min(...rates);out.textContent=`תוספת הרווח בפועל${items.length>1?' הנמוכה ביותר':''}: ${min.toFixed(1)}% על העלות ללא פיקדון ואריזה`;if(min<mark(sign.markup)/100-.05)out.classList.add('warning');}}catch{}
}
function renderSigns(){updateCounts();$('#sign-editors').innerHTML=state.signs.length?state.signs.map(editor).join(''):'<div class="empty-state">בחר מוצר מהתעודה כדי להכין שלט.<br><button class="secondary" data-back-document>לבחירת מוצרים</button></div>';state.signs.forEach(updateRecommendation);renderPreview();}
function drawData(sign){const v=signValidity(sign);return {...sign,valid:v.ok,priceCents:v.ok?saleFor(sign,v.rows[0].row,v.rows[0].units):0,oldCents:sign.oldPrice?(()=>{try{return amount(sign.oldPrice,'מחיר קודם')}catch{return 0}})():0,pct:decimal(sign.pct),validUntil:sign.validUntil?sign.validUntil.split('-').reverse().join('.'):'',qty:sign.qty};}
function renderPreview(){clearTimeout(previewTimer);$('#preview-area').hidden=!state.signs.length;if(!state.signs.length){state.canvases=[];return;}state.canvases=renderPages(state.signs.map(drawData),state.perPage,prefs.storeName);const area=$('#preview-pages');area.replaceChildren();state.canvases.forEach((canvas,i)=>{const div=document.createElement('div');div.className='preview-page';canvas.setAttribute('aria-label',`תצוגת דף שלטים ${i+1}`);div.append(canvas);const controls=document.createElement('div');controls.className='preview-page-controls';controls.innerHTML=`<span>דף ${i+1} מתוך ${state.canvases.length}</span><button data-save-page="${i}">שמירת הדף כתמונה</button>`;div.append(controls);area.append(div);});}
function schedulePreview(){clearTimeout(previewTimer);previewTimer=setTimeout(renderPreview,120);}
function validateAll(){let ok=true;for(const s of state.signs){const v=signValidity(s);const e=$('#error-'+s.id);e.hidden=v.ok;e.textContent=v.error||'';if(!v.ok)ok=false;}if(!ok){toast('יש להשלים את הפרטים המסומנים לפני שמירה');document.querySelector('.sign-error:not([hidden])')?.scrollIntoView({behavior:'smooth',block:'center'});}return ok&&state.signs.length>0;}
function png(canvas){return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('יצירת התמונה נכשלה')),'image/png'));}
function download(blob,name){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function savePage(i){if(!validateAll())return;renderPreview();try{const blob=await png(state.canvases[i]);download(blob,`signs-${i+1}.png`);toast('התמונה מוכנה לשמירה');}catch(e){toast(e.message);}}
async function share(){if(!validateAll())return;renderPreview();try{const files=await Promise.all(state.canvases.map(async(c,i)=>new File([await png(c)],`signs-${i+1}.png`,{type:'image/png'})));if(navigator.canShare?.({files})){await navigator.share({files,title:'שלטי מבצע'});}else if(files.length===1){download(files[0],files[0].name);}else{toast('לחץ על ״שמירת הדף כתמונה״ מתחת לכל דף');}}catch(e){if(e.name!=='AbortError')toast('השיתוף לא זמין בדפדפן הזה. אפשר לשמור כל דף כתמונה.');}}
function print(){if(!validateAll())return;renderPreview();const area=$('#print-root');area.replaceChildren();for(const c of state.canvases){const img=new Image();img.src=c.toDataURL('image/png');area.append(img);}Promise.all([...area.children].map(i=>i.decode())).then(()=>window.print()).catch(()=>toast('לא ניתן להכין את ההדפסה'));}
function editProducts(id){const sign=state.signs.find(s=>s.id===id);state.editProducts=id;$('#product-options').innerHTML=state.doc.rows.map(r=>`<label class="option-row"><input type="checkbox" value="${r.id}" ${sign.productIds.includes(r.id)?'checked':''}><span>${esc(r.name)}</span></label>`).join('');$('#products-dialog').showModal();}
$('#upload-button').addEventListener('click',pickFile);$('#pdf-file').addEventListener('change',e=>loadFile(e.target.files[0]));
$('#document-tab').addEventListener('click',()=>showView('document'));$('#signs-tab').addEventListener('click',()=>showView('signs'));$('#add-sign').addEventListener('click',()=>{showView('document');toast('בחר מוצר או כמה מוצרים מהתעודה');});
$('#separate-signs').addEventListener('click',()=>addSigns(false));$('#shared-sign').addEventListener('click',()=>addSigns(true));
document.addEventListener('click',e=>{
  const b=e.target.closest('button');if(!b)return;
  if(b.dataset.action==='upload')pickFile();
  if(b.dataset.sign)addSigns(false,[b.dataset.sign]);
  if(b.hasAttribute('data-back-document'))showView('document');
  if(b.dataset.delete){state.signs=state.signs.filter(s=>s.id!==b.dataset.delete);renderSigns();}
  if(b.dataset.editProducts)editProducts(b.dataset.editProducts);
  if(b.dataset.kind){const s=state.signs.find(s=>s.id===b.dataset.id);s.kind=b.dataset.kind;renderSigns();}
  if(b.dataset.apply){const s=state.signs.find(s=>s.id===b.dataset.apply);try{const r=recommendation(s);s[r.type==='pct'?'pct':'price']=r.type==='pct'?String(r.value):(r.value/100).toFixed(2);renderSigns();}catch(e){toast(e.message);}}
  if(b.dataset.savePage!==undefined)savePage(Number(b.dataset.savePage));
});
document.addEventListener('change',e=>{
  const el=e.target;
  if(el.dataset.select){if(el.checked)state.selected.add(el.dataset.select);else state.selected.delete(el.dataset.select);el.closest('.product-card').classList.toggle('selected',el.checked);updateSelection();}
  if(el.name==='layout'){state.perPage=Number(el.value);renderPreview();}
  if(el.dataset.rounding){const s=state.signs.find(s=>s.id===el.dataset.rounding);s.rounding=el.checked?'ninety':'exact';updateRecommendation(s);}
});
document.addEventListener('input',e=>{const el=e.target;if(!el.dataset.id)return;const s=state.signs.find(s=>s.id===el.dataset.id);if(!s)return;if(el.dataset.field)s[el.dataset.field]=el.value;if(el.dataset.units)s.units[el.dataset.units]=el.value;updateRecommendation(s);$('#error-'+s.id).hidden=true;schedulePreview();});
$('#settings-button').addEventListener('click',()=>{$('#store-name').value=prefs.storeName;$('#default-markup').value=prefs.markup;$('#settings-dialog').showModal();});
$('#save-settings').addEventListener('click',()=>{try{mark($('#default-markup').value);prefs={storeName:$('#store-name').value.trim(),markup:decimal($('#default-markup').value)};try{localStorage.setItem('coca-prefs-v1',JSON.stringify(prefs));}catch{toast('הדפדפן אינו מאפשר לשמור הגדרות; הן בתוקף למפגש הנוכחי');}$('#settings-dialog').close();if(state.view==='signs')renderPreview();}catch(e){toast(e.message);}});
$('#close-products').addEventListener('click',()=>$('#products-dialog').close());$('#save-products').addEventListener('click',()=>{const ids=[...$('#product-options').querySelectorAll('input:checked')].map(i=>i.value);if(!ids.length){toast('בחר לפחות מוצר אחד');return;}const s=state.signs.find(s=>s.id===state.editProducts);s.productIds=ids;ids.forEach(id=>s.units[id]??='');$('#products-dialog').close();renderSigns();});
$('#share-signs').addEventListener('click',share);$('#print-signs').addEventListener('click',print);
window.addEventListener('beforeunload',e=>{if(state.signs.length){e.preventDefault();e.returnValue='';}});
